# Generated by Django 3.2.5 on 2021-10-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0002_blood_donate_hid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_donate',
            name='hid',
        ),
        migrations.AddField(
            model_name='request_blood',
            name='hid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnose.blood_bank'),
        ),
    ]
