# Generated by Django 3.2.5 on 2021-10-10 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0005_request_blood_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donate',
            name='bgroup',
            field=models.CharField(default='O+', max_length=10),
        ),
        migrations.AlterField(
            model_name='blood_donate',
            name='date',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='blood_donate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnose.blood_bank'),
        ),
    ]
