# Generated by Django 3.2.5 on 2021-10-10 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0006_auto_20211010_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donate',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 10)),
        ),
    ]
